# Game Configuration
from enum import Enum
import pygame

GAME_WIDTH = 600
GAME_HEIGHT = 150
GAME_NAME = "Dino Soar"
GROUND_Y = GAME_HEIGHT - 15
SCROLLING_SPEED_START = 5
SCROLLING_SPEED_INCREMENT = 1
FONT_SIZE = 13
SCORE_POINTS_PER_MILLISECOND = 0.01
SCORE_X = GAME_WIDTH - 80
SCORE_Y = 10
MESSAGE_X = GAME_WIDTH//2
MESSAGE_Y = GAME_HEIGHT//2 - 25
MESSAGE_LINE_SPACING = 3
DINO_JUMP_SPEED = -8
DINO_GRAVITY = .4
DINO_START_X = 0
DINO_START_Y = GROUND_Y
DINO_ANIMATION_SPEED = 0.1
FPS = 60
COLOR_BACKGROUND = (255, 255, 255)
COLOR_FOREGROUND = (83, 83, 83)

class GAME_EVENT_TYPES(Enum):
    CRASH = pygame.event.custom_type()
    SPAWNED = pygame.event.custom_type()

class SCREEN_LAYERS(Enum):
    GROUND = 0
    OBSTACLES = 1
    DINO = 2
    UI = 3

